In [89]:
l <- list(
    mapply(assign, letters, 1:26),
    A = array(1:60, c(5,2,3)),
    M = matrix(1:50, c(10,5))
)

In [56]:
l

$Alphabet
 a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

$`Numbers to 30`
, , 1

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

, , 2

     [,1] [,2]
[1,]   11   16
[2,]   12   17
[3,]   13   18
[4,]   14   19
[5,]   15   20

, , 3

     [,1] [,2]
[1,]   21   26
[2,]   22   27
[3,]   23   28
[4,]   24   29
[5,]   25   30


$`Numbers to 50`
      [,1] [,2] [,3] [,4] [,5]
 [1,]    1   11   21   31   41
 [2,]    2   12   22   32   42
 [3,]    3   13   23   33   43
 [4,]    4   14   24   34   44
 [5,]    5   15   25   35   45
 [6,]    6   16   26   36   46
 [7,]    7   17   27   37   47
 [8,]    8   18   28   38   48
 [9,]    9   19   29   39   49
[10,]   10   20   30   40   50

In [57]:
l[1]

$Alphabet
 a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26

In [86]:
names(l) <- c("Alphabet", "Numbers_to_30", "Numbers_to_50") ## Giving clearer names to the three groups in the list


In [21]:
l

$Alphabet
 a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

$`Numbers to 30`
, , 1

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

, , 2

     [,1] [,2]
[1,]   11   16
[2,]   12   17
[3,]   13   18
[4,]   14   19
[5,]   15   20

, , 3

     [,1] [,2]
[1,]   21   26
[2,]   22   27
[3,]   23   28
[4,]   24   29
[5,]   25   30


$`Numbers to 50`
      [,1] [,2] [,3] [,4] [,5]
 [1,]    1   11   21   31   41
 [2,]    2   12   22   32   42
 [3,]    3   13   23   33   43
 [4,]    4   14   24   34   44
 [5,]    5   15   25   35   45
 [6,]    6   16   26   36   46
 [7,]    7   17   27   37   47
 [8,]    8   18   28   38   48
 [9,]    9   19   29   39   49
[10,]   10   20   30   40   50

In [82]:
Consonants <- list(Alphabet = 2:4, 6:8, 10:14, 16:20, 22:26) ## Separating the consonants from the rest of the alphabet


$Alphabet
[1] 2 3 4

[[2]]
[1] 6 7 8

[[3]]
[1] 10 11 12 13 14

[[4]]
[1] 16 17 18 19 20

[[5]]
[1] 22 23 24 25 26

In [83]:
Consonants

$Alphabet
[1] 2 3 4

[[2]]
[1] 6 7 8

[[3]]
[1] 10 11 12 13 14

[[4]]
[1] 16 17 18 19 20

[[5]]
[1] 22 23 24 25 26

In [92]:
 Numbers_to_30 <- array(1:60, c(5,2,3))

ERROR: Error in l[[c(1, 5, 9, 15, 21)]]: recursive indexing failed at level 2



ERROR: Error in Numbers_to_30[c(T, F), c(T, F)]: incorrect number of dimensions


In [113]:
M <- matrix(1:50, c(10,5))

In [114]:
M

[,1] [,2] [,3] [,4] [,5]
 [1,]  1   11   21   31   41  
 [2,]  2   12   22   32   42  
 [3,]  3   13   23   33   43  
 [4,]  4   14   24   34   44  
 [5,]  5   15   25   35   45  
 [6,]  6   16   26   36   46  
 [7,]  7   17   27   37   47  
 [8,]  8   18   28   38   48  
 [9,]  9   19   29   39   49  
[10,] 10   20   30   40   50

In [119]:
M[c(T,F), ]  ## recycling a logical vector for the rows

[,1] [,2] [,3] [,4] [,5]
[1,] 1    11   21   31   41  
[2,] 3    13   23   33   43  
[3,] 5    15   25   35   45  
[4,] 7    17   27   37   47  
[5,] 9    19   29   39   49

In [121]:
M[c(T,F), ]

[,1] [,2] [,3] [,4] [,5]
[1,] 1    11   21   31   41  
[2,] 3    13   23   33   43  
[3,] 5    15   25   35   45  
[4,] 7    17   27   37   47  
[5,] 9    19   29   39   49

In [124]:
set.seed(2022)
vec <- sample(c("1", "0", "o"), size = 100, replace = TRUE)
typeof(vec)

[1] "character"

In [139]:
## It's a character vector. Proportion of the vector elements did we fail to convert correctly is a third.
vec <- sample(c("1", "0", "o"), size = 100, replace = TRUE)
vec_new <- replace(vec, 3, "0")
vec_new                     


[1] "1" "0" "0" "1" "o" "o" "0" "o" "1" "o" "0" "o" "o" "0" "1" "1" "o" "o"
 [19] "0" "1" "0" "o" "1" "0" "1" "0" "1" "0" "0" "o" "o" "0" "o" "1" "1" "1"
 [37] "0" "0" "0" "o" "o" "o" "o" "o" "1" "0" "1" "0" "0" "0" "1" "o" "0" "1"
 [55] "o" "o" "o" "0" "1" "o" "o" "o" "0" "1" "1" "o" "1" "0" "o" "0" "1" "o"
 [73] "0" "0" "o" "o" "0" "0" "0" "o" "0" "o" "0" "o" "1" "0" "1" "0" "0" "1"
 [91] "0" "0" "0" "o" "1" "o" "o" "1" "1" "1"

[1] "0" "0" "o" "o" "0" "1" "0" "0" "1" "0" "o" "o" "o" "o" "0" "0" "o" "o"
 [19] "0" "o" "o" "1" "1" "1" "1" "1" "o" "o" "0" "1" "1" "0" "0" "1" "0" "0"
 [37] "1" "1" "0" "0" "o" "1" "1" "0" "0" "o" "o" "0" "1" "0" "o" "o" "o" "1"
 [55] "1" "0" "o" "o" "1" "o" "o" "0" "1" "0" "0" "o" "0" "1" "o" "0" "1" "o"
 [73] "0" "0" "o" "o" "1" "0" "o" "1" "o" "0" "1" "0" "o" "0" "1" "0" "1" "o"
 [91] "o" "1" "o" "o" "0" "o" "1" "o" "o" "o"

In [140]:
books <- c(
  "Dubliners",
  "Ulysses",
  "War and Peace",
  "Normal People",
  "Crime and Punishment",
  "The Picture of Dorian Gray"
)

In [141]:
books ## This is the list of elements

[1] "Dubliners"                  "Ulysses"                   
[3] "War and Peace"              "Normal People"             
[5] "Crime and Punishment"       "The Picture of Dorian Gray"

In [142]:
length(books)

[1] 6

In [143]:
nchar(books) ## this gives the number of characters in each title

[1]  9  7 13 13 20 26

In [144]:
mean(nchar(books)) ## This gives the mean of each value

[1] 14.66667

In [147]:
set.seed(2022)
educ <- rpois(1000, 2)
educ <- ifelse(educ > 4, 4, educ)

In [148]:
typeof(educ)

[1] "double"

In [158]:
Factors<-c(" No Formal Education","Primary Education","Secondary Education", "College Education", "Post-graduate Education" )
Factors = 1:5
Factors

[1] 1 2 3 4 5

In [159]:
table(Factors)

Factors
1 2 3 4 5 
1 1 1 1 1 

In [161]:
char_1 <- unlist(strsplit("kitten", split = ""))
char_2 <- unlist(strsplit("sitting", split = ""))

In [162]:
char_1

[1] "k" "i" "t" "t" "e" "n"

In [163]:
char_2

[1] "s" "i" "t" "t" "i" "n" "g"

In [179]:
replace(char_1, c("k", c("s")

ERROR: Error in parse(text = x, srcfile = src): <text>:2:0: unexpected end of input
1: replace(char_1, c("k", c("s")
   ^


In [180]:
replace(char_1, c("k"), c("s"))




k 
"k" "i" "t" "t" "e" "n" "s"