In [1]:
options(jupyter.rich_display = FALSE)

# Assignment 1: R Basics and Control Flow

## POP77001 Computer Programming for Social Scientists

## Before submission

- Make sure that you can run all cells without errors
- You can do it by clicking `Kernel`, `Restart & Run All` in the menu above
- Make sure that you save the output by pressing Command+S / CTRL+S
- Rename the file from `01_assignment.ipynb` to `01_assignment_lastname_firstname_studentnumber.ipynb`
- Use Firefox browser for submitting your Jupyter notebook on Blackboard

## Exercise 1: Subsetting (20 points)

Write 3 separate subsetting operations to extract the following elements from the list below:
- All consonants from the first character vector
- Second columns in all dimensions from the array A
- Odd rows from the matrix M

In [2]:
l <- list(
    mapply(assign, letters, 1:26),
    A = array(1:60, c(5,2,3)),
    M = matrix(1:50, c(10,5))
)

[[1]]
 a  b  c  d  e  f  g  h  i  j  k  l  m  n  o  p  q  r  s  t  u  v  w  x  y  z 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

$A
, , 1

     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

, , 2

     [,1] [,2]
[1,]   11   16
[2,]   12   17
[3,]   13   18
[4,]   14   19
[5,]   15   20

, , 3

     [,1] [,2]
[1,]   21   26
[2,]   22   27
[3,]   23   28
[4,]   24   29
[5,]   25   30


$M
      [,1] [,2] [,3] [,4] [,5]
 [1,]    1   11   21   31   41
 [2,]    2   12   22   32   42
 [3,]    3   13   23   33   43
 [4,]    4   14   24   34   44
 [5,]    5   15   25   35   45
 [6,]    6   16   26   36   46
 [7,]    7   17   27   37   47
 [8,]    8   18   28   38   48
 [9,]    9   19   29   39   49
[10,]   10   20   30   40   50


In [34]:
# Exercise 1:





SyntaxError: invalid syntax (1843579448.py, line 4)

## Exercise 2: Working with vectors  (20 points)

Look at the vector below. What is its type? Convert it into numeric. Note that some values get missing due to letter `o` used instead of digit `0`. What proportion of the vector elements did we fail to convert correctly? Now let us fix this issue. Using either subsetting and assignment or `ifelse()` function replace all `NA`s in the converted numeric vector into `0` (zeros).

In [39]:
set.seed(2022)
vec <- sample(c("1", "0", "o"), size = 100, replace = TRUE)
typeof(vec)

AttributeError: type object 'set' has no attribute 'seed'

In [6]:
# Exercise 2:

# Your code goes here
> letters.list <- list("a", "b",  "c",  "d",  "e",  "f",  "g",  "h",  "i",  "j",  "k",  "l",  "m",  "n",  "o",  "p",  "q", "r",  "s",  "t",  "u",  "v",  "w",  "x",  "y",  "z")

letters <- list (a, b,  c,  d,  e,  f,  g,  h,  i,  j,  k,  l,  m,  n,  o,  p,  q, r,  s,  t,  u,  v,  w,  x,  y,  z)
l [-c(1, 5, 9, 15, 21)]

## Exercise 3: Vectorized operations  (20 points)

Using function `mean()` calculate the percentage of book titles in the vector below that have more than 10 characters in them (including whitespaces).

Tip: You can use `nchar()` function to calculate the number of characters in a vector

In [8]:
# Exercise 3:

# Your code goes here

## Exercise 4: Attributes and factors  (20 points)

Suppose you read in a variable which represents education of survey respondents. After consulting the codebook for this survey you determined that specific values that the variable takes are coded as follows:

- `0` - No formal education
- `1` - Primary Education
- `2` - Secondary Education
- `3` - College Education
- `4` - Post-graduate Education

Convert the variable `educ` below into a factor variable with each value coded explicitly as one of the education levels. Tabulate the variable using `table()` function. Change the order of the levels of this factor variable such that the most common education level is the first (baseline/reference) category (you can leave other education levels in their origianl order). Tabulate the variable again.   

In [40]:
set.seed(2022)
educ <- rpois(1000, 2)
educ <- ifelse(educ > 4, 4, educ)


AttributeError: type object 'set' has no attribute 'seed'

In [10]:
# Exercise 4:

# Your code goes here

## Exercise 5: Conditional statements and loops  (20 points)

[Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) is a string distance metric that measures how many transformations (insertion, deletion, substitution) are required to convert one string into another. For example, consider words 'cat' and 'can'. Letter 't' in the first word can be substituted with a character 'n' in order for the two words to become identical.

For classical Levenshtein distance each of the transformations has the same cost of 1. In other words, the distance (of 1) is the same between the word pairs 'cat' - 'can' and 'cat' - 'cats'.

Below you can see two character vectors that were transformed to have a single letter as an individual element. Write a loop to compare each of the elements from one string to each of the elements from another string while keeping track of the number of transformations. Print out the result of the transformations count.

In [11]:
char_1 <- unlist(strsplit("kitten", split = ""))
char_2 <- unlist(strsplit("sitting", split = ""))

In [12]:
char_1

[1] "k" "i" "t" "t" "e" "n"

In [13]:
char_2

[1] "s" "i" "t" "t" "i" "n" "g"

In [14]:
# Exercise 5:

# Your code goes here